### ISSUE TITLE
Eager macro-expansion failure with `use-package`

### ISSUE THREAD

**Issue by swarnendubiswas** [rnkn/olivetti#74] opened 2023-07-29 08:48 UTC
I use Olivetti with `use-package` and `straight.el` on Emacs 29.1 RC1. My Olivetti config is simple.

```
(use-package olivetti
  :hook
  ((text-mode-hook prog-mode-hook) . olivetti-mode) 
  :custom (olivetti-body-width 108)
  :diminish)
```

However, I often get the following error on Emacs start. 

```
Eager macro-expansion failure: (error "Eager macro-expansion skipped due to cycle:
  … => (load \"olivetti.el\") => (macroexpand-all …) => (macroexpand (eval-when-compile …)) => (load \"olivetti.el\")")
```

I can reproduce this error consistently with the following MWE with Emacs 29.1 RC1 and `emacs -nw -q`. I have also got this error quite a few times across different Emacs versions, 27.1 and 28.2. 

```
(setq straight-build-dir (format "build/%d%s%d"
                                 emacs-major-version
                                 version-separator
                                 emacs-minor-version)
      straight-use-package-by-default t)

(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq use-package-hook-name-suffix nil)
(straight-use-package 'use-package)

(use-package olivetti
  :hook
  ((text-mode-hook prog-mode-hook) . olivetti-mode) ; `emacs-startup-hook' does not work
  :custom (olivetti-body-width 108)
  :diminish)
```

**Comment by larstvei** [comment] 2023-08-06 21:01
As far as I can see, there is nothing in the olivetti source that causes this error. I could not reproduce the error on a recent build (GNU Emacs 30.0.50).

I can see from the [`straight.el` docs](https://github.com/radian-software/straight.el#getting-started) that it is recommended to set

```elisp
(setq package-enable-at-startup nil)
```

to their [early init-file](https://www.gnu.org/software/emacs/manual/html_node/emacs/Early-Init-File.html). Perhaps this is worth trying out (consider this a bit of a shot in the dark from my part).

I will be glad to address any olivetti issue, but as I can't see any change that I can make to `olivetti.el` that would help you, I'll close the issue for now.

**Closed by larstvei** 2023-08-06 21:01 UTC
