### ISSUE TITLE
After shrinked buffer is closed, other buffers remain shrinked as well 

### ISSUE THREAD

**Issue by kchousos** [rnkn/olivetti#73] opened 2023-06-27 14:40 UTC
Hello,

First of all, thanks for this great package. I've been facing a weird issue where if I open e.g. an org-mode file, where there is a `olivetti-mode` hook for org-mode, after I close that buffer, the buffer that is displayed after is itself narrowed as well. Is there any solution? My relevant config is the following:

```elisp
(use-package olivetti
  :elpaca t
  :hook
  (org-mode . olivetti-mode)
  (markdown-mode . olivetti-mode)
  (Info-mode . olivetti-mode)
  (elpher-mode . olivetti-mode)
  (eww-mode . olivetti-mode)
  (TeX-mode . olivetti-mode)
  (tex-mode . olivetti-mode)
  (LaTeX-mode . olivetti-mode)
  (latex-mode . olivetti-mode))

(add-hook 'olivetti-mode-on-hook (lambda () (olivetti-set-width 130)))
```

Thanks in advance.

**Comment by larstvei** [comment] 2023-06-27 22:48
Hi!

Thanks for reporting. Sadly, I am not able to reproduce this. Are you able to reproduce this using `emacs -Q`?

This isn't related, but you can set the default body-width like this in the `:config` of your `use-package` expression, instead of setting it via a hook:
```emacs-lisp
(setq-default olivetti-body-width 130)
```

**Comment by larstvei** [comment] 2023-07-10 20:32
I am closing this due to not being able to reproduce.

**Closed by larstvei** 2023-07-10 20:32 UTC
